input {
  http {
    port => 5044
    codec => json
  }
}

filter {

  #
  # Parse JSON from Cortex
  #
  json {
    source => "message"
    skip_on_invalid_json => true
  }

  #
  # Ensure numeric timestamp
  #
  mutate {
    convert => {
      "detection_timestamp" => "integer"
      "event_timestamp"     => "integer"
    }
  }

  #
  # Use the original time of the alert as the @timestamp
  #
  if [detection_timestamp] {
    date {
      match  => ["detection_timestamp", "UNIX_MS"]
      target => "@timestamp"
    }
  } else if [event_timestamp] {
    date {
      match  => ["event_timestamp", "UNIX_MS"]
      target => "@timestamp"
    }
  } else if [creation_time] {
    date {
      match  => ["creation_time", "UNIX_MS"]
      target => "@timestamp"
    }
  }

  #
  # Use alert_id as Elasticsearch _id
  # so that duplication does not occur with each cron pull
  #
  if [alert_id] {
    mutate {
      add_field => { "[@metadata][_id]" => "%{alert_id}" }
    }
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user  => "YOUR-ELASTIC-USER"
    password => "YOUR-ELASTIC-PASSWORD"

    index => "cortex-alerts"
    document_id => "%{[@metadata][_id]}"

    ilm_enabled => false
  }

  stdout {
    codec => rubydebug
  }
}
